### ISSUE TITLE
SQL injection

### ISSUE THREAD

**Issue by davidsarkany** [lanszkicsaba/vallalatiranyitasirendszer#1]
A loginnál és a regnél láttam, hogy simán stringként rakjátok össze a queryket.
Az SQL injection veszélyes.
https://stackoverflow.com/questions/60174/how-can-i-prevent-sql-injection-in-php

**Comment by lanszkicsaba** [comment]
Köszönjük szépen a segítséged, amint tudom módosítom :)

**Comment by Morettihun** [comment]
Kedves Dávid!

Köszönjük az észrevételt és a segítséget. Természetesen Statementekkel lesz mindenhol megoldva (lsd useredit.php kód). Ez egy iskolai házi projekt, mindenki okul és tanul! :smile: Főleg az ilyen építő kritikákból.

Szép napot neked.
